Adds missing tests and refactors
cadmiumcat/books-api pull request #35
Opened 2021-04-14 13:37 UTC by cadmiumcat

### This PR

- Adds missing tests for `GET /books/{id}` and `GET /books`
- Removes unsued checkin/out functions
- Renames handler functions for clarity

#### Remaining questions:
- how can I test the [`Setup` function in `api.go`](https://github.com/cadmiumcat/books-api/blob/da7a4c61bc45f814190a512e831708b55d6fe49b/api/api.go#L23)?

2021-04-16 16:01 UTC, nshumoogum requested changes

2021-04-16 16:01 UTC, nshumoogum commented on api/books_test.go
> +				So(response.Body.String(), ShouldEqual, "unexpected error in MongoDB\n")
Same as above

2021-04-16 16:28 UTC, cadmiumcat commented on api/books_test.go
> +				So(response.Body.String(), ShouldEqual, "unexpected error in MongoDB\n")
That's interesting. I created the `mockDataStore` such that `GetBookFunc` returns an error I would never actually return. "unexpected error in MongoDB` only exists in the tests.
Any unexpected error from the `GetBook` function would be wrapped in "unexpected error when getting a book" https://github.com/cadmiumcat/books-api/blob/a56b6e6cc7d9ba469cfec39da85af78ebc4f22da/mongo/mongo.go#L80

So I guess what I'm testing is that the error makes it to the response body?

2021-04-19 09:33 UTC, nshumoogum commented on api/books_test.go
> +				So(response.Body.String(), ShouldEqual, "unexpected error in MongoDB\n")
So I would mask the error from mongo db back to the api user, and just return a message saying `internal server error`. The API user cannot do anything to help their situation at this point.

By giving them more information they might be able to exploit the situation (assuming they have malicious intent).

2021-04-19 15:20 UTC, nshumoogum approved these changes

2021-04-19 15:44 UTC, merged